### ISSUE TITLE
Attached gpx file not loaded

### ISSUE THREAD

**Issue by ShelleyLake** [BourgeoisLab/GPXLab#22] opened 2019-11-12 10:49 UTC
@BourgeoisLab 
The attached gpx file is not loaded at all.
Nothing is shown in the map and the list of the tracks/points is empty.

[2019-01-19T10_20_18Z.zip](https://github.com/BourgeoisLab/GPXLab/files/3835714/2019-01-19T10_20_18Z.zip)

**Comment by sikmir** [comment] 2019-11-12 11:04
That's caused by:
```xml
<gpx
version="1.1"
```
Newline delimiter is used between tag and attribute. Adding whitespace after 'gpx' fixes the problem. GPX parser should be fixed.

**Comment by BourgeoisLab** [comment] 2019-11-12 18:29
@sikmir I was curious about it and already fix it.
If you made some changes on your side, I will wait for your commit to merge both codes.

**Comment by sikmir** [comment] 2019-11-12 18:57
@BourgeoisLab No problem, go ahead and commit your fix. I haven’t commit anything yet, just figured out the root cause.

**Comment by BourgeoisLab** [comment] 2019-11-12 19:44
Fixed with 0340626684b2c2042fc280a9fad2bfd97570c7b3.

**Closed as completed by BourgeoisLab** 2019-11-12 19:44 UTC
Labels: bug
